/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.brayvasq.farm

/**
 * Main file. It will executes the app
 *
 * @author brayvasq
 * @version 0.2
 */
fun main(args: Array<String>) {
    Commands(args).process()
}
